export default [
	{
		languages: ['Next.js', 'TypeScript', 'Docker', 'Vercel', 'MongoDB'],
		name: 'CALCULADORA FREELANCER',
		description: [
			'Como parte do meu aprendizado em Next.js e MongoDB, desenvolvi uma aplicação web desenvolvida para ajudar freelancers a calcular o valor mínimo por hora que precisam cobrar para cobrir todos os custos e atingir a lucratividade desejada.',
			'',
			'🛠️ Tecnologias Utilizadas',
			'',
			'Framework: Next.js com App Router',
			'Banco de Dados: MongoDB em container Docker',
			'Autenticação: Sistema seguro com salt e hash',
			'Testes: Suíte de testes unitários com cobertura',
			'',
			'Funcionalidades Implementadas',
			'',
			'🧮 Calculadora de Precificação',
			'',
			'- Cálculo de custos mensais: Inclui impostos, luz, internet, software, equipamentos e outros gastos',
			'- Horas Trabalhadas: Cadastro de horas por dia e dias da semana',
			'- Lucro Desejado: Cadastro do valor de lucro desejado',
			'- Minhas Despesas Mensais: Cadastro de uma lista de Despesas Mensais',
			'- Meus Projetos: Cadastro de uma lista de Projetos',
			'- Valor hora ideal: Calcula o preço mínimo por hora para atingir suas metas',
			'',
			'📊 Dashboard Financeiro',
			'',
			'- Visualização de quanto Você Precisa Cobrar baseado em suas despesas, horas por dia, dias da semana e lucro desejado',
			'- Visualização de quanto Você Está Recebendo baseado nos projetos cadastrados',
			'',
			'🔐 Autenticação Segura',
			'',
			'- Sistema de login para acesso privado aos dados',
			'- Proteção de informações financeiras sensíveis',
		],
		date: 'Setembro de 2025',
		links: {
			Demonstração: 'https://calculadora-freelancer-one.vercel.app/',
			GitHub: 'https://github.com/senomardetritos/calculadora-freelancer',
		},
		images: ['images/calcfreela/dashboard.png', 'images/calcfreela/login.png', 'images/calcfreela/register.png', 'images/calcfreela/hours.png', 'images/calcfreela/profit.png', 'images/calcfreela/expenses.png', 'images/calcfreela/edit-expenses.png', 'images/calcfreela/projects.png', 'images/calcfreela/edit-projects.png'],
	},{
		languages: ['Angular', 'TypeScript', 'Node', 'Express', 'AWS', 'MySql'],
		name: 'POSTS ANGULAR + EXPRESS',
		description: [
			'Como parte do meu aprendizado em Angular, RxJS, TypeScript e testes com Jest, desenvolvi uma rede social para praticar conceitos avançados de front-end, back-end e banco de dados. O projeto simula as funcionalidades básicas de uma plataforma de postagens, com interações em tempo real via WebSocket.',
			'',
			'Tecnologias Utilizadas',
			'- Front-end: Angular (Componentes reativos com RxJS)',
			'- Back-end: Node.js + Express (API RESTful)',
			'- Banco de Dados: MySQL (Armazenamento de usuários e postagens)',
			'- Testes: Jest (Unitários)',
			'- Real-time: WebSocket (Chat)',
			'',
			'Funcionalidades Implementadas',
			'',
			'✅ Autenticação segura',
			'- Cadastro e login de usuários',
			'- Recuperação de senha via e-mail',
			'- Tokens JWT para sessões',
			'',
			'✅ Postagens e Interações',
			'- Criar, editar e excluir postagens de texto',
			'- Comentar e curtir (like) publicações',
			'- Busca por postagens ou usuários',
			'',
			'✅ Rede Social',
			'- Perfil com upload de foto',
			'- Perfil com contagem de postagens, seguindo e seguidores',
			'- Seguir e ser seguido (sistema de amigos)',
			'- Feed personalizado com postagens de quem você segue',
			'',
			'✅ Chat em Tempo Real',
			'- WebSocket para mensagens instantâneas',
			'- Notificações de novas mensagens',
			'',
			'✅ Responsividade',
			'- Ajusta para ser exibido corretamente em computador, tablet ou celular.',
			'',
			'✅ Servidores',
			'- Front-end: Hostgator',
			'- Back-end: Elastic Beanstalk da AWS',
			'- Banco de dados: Hostgator',
			'',
			'Desafios e Aprendizados',
			'- Gestão de estado complexo com RxJS (observables para dados reativos)',
			'- Testes robustos com Jest (100% de cobertura de código)',
			'- Otimização de queries SQL para o feed de postagens',
			'- Sincronização em tempo real entre clientes via WebSocket',
		],
		date: 'Agosto de 2025',
		links: {
			GitHub: 'https://github.com/senomardetritos/posts-angular-express',
		},
		images: ['images/posts-angular/01.png', 'images/posts-angular/02.png', 'images/posts-angular/03.png', 'images/posts-angular/04.png', 'images/posts-angular/05.png', 'images/posts-angular/06.png', 'images/posts-angular/07.png', 'images/posts-angular/08.png', 'images/posts-angular/09.png', 'images/posts-angular/10.png'],
	},
	{
		languages: ['React', 'TanStack Query', 'TypeScript', 'Scss'],
		name: 'INSTA GIT',
		description: [
			'Recriei a interface do Instagram, utilizando dados da API do GitHub para exibir informações de repositórios e atividades de usuários. Este projeto foi uma oportunidade valiosa para aprimorar habilidades técnicas e explorar conceitos avançados de desenvolvimento front-end.',
			'',
			'Principais Funcionalidades Implementadas:',
			'',
			'✅ Consumo de API GitHub: Exibição dinâmica de repositórios, seguidores e atividades de usuários.',
			'✅ Interface Interativa: Recriação fiel da UI do Instagram, incluindo navegação, curtidas e visualização de perfis.',
			'✅ Gerenciamento de Estado: Controle eficiente de dados e estados da aplicação para uma experiência fluida.',
			// '✅ Design Responsivo: Adaptação para diferentes dispositivos (mobile, tablet e desktop).',
			'',
			'Tecnologias Utilizadas:',
			'',
			'Front-end: React',
			'Estilização: SCSS',
			'Gerenciamento de Estado: TanStack Query',
			'APIs: GitHub REST API para dados de usuários e repositórios.',
			'',
			'Aprendizados e Destaques:',
			'',
			'Prática avançada em consumo de APIs RESTful e manipulação de dados JSON.',
			'Implementação de roteamento e navegação entre perfis simulados.',
			'Exploração de conceitos de UI/UX para replicar uma interface complexa e conhecida.',
			'Consolidação de conhecimentos em componentização reutilizável e organização de código.',
			'',
			'Resultados:',
			'',
			'Interface visualmente atraente e funcional, com integração simulada de dados.',
			'Código modular e bem estruturado, facilitando manutenção e escalabilidade.',
			'Demonstração de habilidades em desenvolvimento front-end moderno e integração com APIs.',
		],
		date: 'Dezembro de 2024',
		links: {
			Demonstração: 'https://senomalabs.com/insta-git',
			GitHub: 'https://github.com/senomardetritos/insta-git',
		},
		images: ['images/instagit/01.png', 'images/instagit/02.png', 'images/instagit/03.png', 'images/instagit/04.png', 'images/instagit/05.png'],
	},
	{
		languages: ['Vue', 'Pinia', 'JavaScript', 'PHP', 'Figma'],
		name: 'UNIVERSITIES APP',
		description: [
			'Desenvolvi uma aplicação web completa para busca e gerenciamento de informações universitárias, utilizando Vue 3 e Pinia para o front-end, e PHP para APIs customizadas. O projeto foi inicialmente prototipado no Figma para garantir uma experiência de usuário otimizada, e utiliza JavaScript como linguagem principal do front-end.',
			'',
			'Tecnologias Utilizadas',
			'',
			'Front-end: Vue 3, Pinia (gerenciamento de estado), JavaScript',
			'Back-end: PHP (API customizada)',
			'Design/Protótipo: Figma',
			'API Externa: universities.hipolabs.com',
			'',
			'Funcionalidades Implementadas',
			'',
			'Busca e Filtros:',
			'✅ Filtrar universidades por país',
			'✅ Buscar instituições por nome',
			'',
			'Sistema de Favoritos:',
			'✅ Adicionar/remover universidades da lista de favoritos',
			'✅ Visualizar lista salva localmente',
			'',
			'Descrição Dinâmica:',
			'✅ Exibição de descrições de universidades via metatags (implementado com API em PHP)',
			'',
			'Interface Responsiva:',
			'✅ Design moderno e adaptativo, inspirado no template Capputeeno',
			'',
			'Objetivos do Projeto:',
			'✅ Praticar gerenciamento de estado com Pinia',
			'✅ Explorar consumo de APIs públicas (universities.hipolabs)',
			'✅ Desenvolver APIs customizadas em PHP para funcionalidades específicas',
			'✅ Implementar componentização reutilizável no Vue',
			'✅ Treinar integração entre front-end e back-end',
			'',
			'Resultados e Aprendizados:',
			'✅ Consolidação de Vue 3 e composição API',
			'✅ Experiência prática com Pinia para estado global',
			'✅ Criação de APIs leves em PHP para processamento de dados',
			'✅ Melhoria nas habilidades de design de UI/UX com Figma',
			'✅ Entendimento aprofundado de manipulação de metadados via back-end',
			'',
			'Integrações:',
			'✅ API Pública: universities.hipolabs.com (dados de universidades)',
			'✅ API Customizada: PHP para extrair meta descrições de sites institucionais',
			'',
			'Este projeto reforçou minha capacidade de criar aplicações full-stack dinâmicas, com foco em performance, usabilidade e código limpo. O uso do Figma garantiu uma interface intuitiva, enquanto o Vue e o Pinia permitiram criar uma experiência interativa e responsiva.',
		],
		date: 'Agosto de 2024',
		links: {
			Demonstração: 'http://senomalabs.com/universities-app',
			API: 'http://universities.hipolabs.com/',
			Figma: 'https://www.figma.com/design/rET9F2CeUEJdiVN7JRu993/E-commerce---capputeeno',
			GitHub: 'https://github.com/senomardetritos/universities-app',
		},
		images: ['images/universities-app/01.png', 'images/universities-app/02.png', 'images/universities-app/03.png', 'images/universities-app/04.png'],
	},
	// {
	// 	languages: ['Vue', 'Vuex'],
	// 	name: 'PANTONE COLORS',
	// 	description: [
	// 		'Desenvolvi uma aplicação utilizando Vue 3 e Vuex para gerenciamento de estado, onde é possível adicionar e remover cores, simulando a experiência de um carrinho de compras. O projeto foi ideal para praticar conceitos como reatividade, manipulação de estados globais e componentização.',
	// 		'Principais funcionalidades implementadas: adicionar cores a uma lista (simulando um carrinho), remover cores da lista de forma dinâmica, gerenciamento centralizado do estado com Vuex, garantindo uma experiência fluida e consistente.',
	// 		'Essa experiência me permitiu consolidar conhecimentos em Vue 3 e explorar boas práticas no uso de Vuex para aplicações mais complexas e interativas.',
	// 	],
	// 	links: {
	// 		Demonstração: 'https://senomalabs.com/pantone-colors',
	// 		API: 'https://reqres.in/api/unknown?page=1',
	// 		GitHub: 'https://github.com/senomardetritos/pantone_colors',
	// 	},
	// 	images: ['images/pantonecolors/01.png', 'images/pantonecolors/02.png'],
	// },
	{
		languages: ['Vue', 'JavaScript', 'LocalStorage'],
		name: 'TO-DO CARD LIST',
		description: [
			'Desenvolvi uma aplicação dinâmica e responsiva para gerenciamento de tarefas, utilizando Vue 3 e JavaScript, com foco na persistência de dados via LocalStorage. O projeto foi idealizado para oferecer uma experiência fluida e intuitiva no organização de atividades diárias.',
			'',
			'Tecnologias Utilizadas',
			'',
			'Front-end: Vue 3 (Composition API), JavaScript (ES6+)',
			'Armazenamento: LocalStorage (persistência de dados no navegador)',
			'Estilização: CSS3 Flexbox/Grid (design responsivo)',
			'',
			'Funcionalidades Implementadas:',
			'✅ Criação dinâmica de tarefas: Adicionar, editar e excluir cartões de tarefas.',
			'✅ Armazenamento local persistente: Os dados são salvos automaticamente no LocalStorage, garantindo que as informações permaneçam disponíveis mesmo após fechar o navegador.',
			'✅ Interface responsiva: Layout adaptável para dispositivos móveis, tablets e desktops.',
			'✅ Componentização modular: Estrutura reutilizável de componentes Vue para escalabilidade.',
			'',
			'Objetivos do Projeto:',
			'✅ Praticar reatividade e gerenciamento de estado com Vue 3.',
			'✅ Implementar persistência de dados sem dependência de back-end.',
			'✅ Explorar design responsivo e acessibilidade.',
			'✅ Desenvolver uma aplicação funcional com baixa complexidade de configuração.',
			'',
			'Resultados e Aprendizados:',
			'✅ Domínio da Composition API do Vue 3 para estruturação de lógica reativa.',
			'✅ Experiência prática com LocalStorage para manipulação de dados locais.',
			'✅ Desenvolvimento de uma interface limpa e intuitiva com feedback visual imediato.',
			'✅ Refatoração de componentes para melhor desempenho e manutenibilidade.',
			'',
			'Diferenciais Técnicos:',
			'✅ Sincronização automática: Alterações refletidas instantaneamente no LocalStorage.',
			'✅ UX aprimorada: Feedback visual ao adicionar/concluir tarefas.',
			'✅ Código modular: Facilidade para adicionar novas funcionalidades (ex.: categorias, prazos).',
			'',
			'Este projeto consolidou meus conhecimentos em Vue 3 e reforçou boas práticas de armazenamento local, demonstrando capacidade de criar aplicações leves, porém robustas, com foco na experiência do usuário. Ideal para demonstração de habilidades em front-end e soluções criativas para problemas cotidianos.',
		],
		date: 'Julho de 2024',
		links: {
			Demonstração: 'https://senomalabs.com/todo-card-list',
			GitHub: 'https://github.com/senomardetritos/todo-card-list',
		},
		images: ['images/to-do/04.png', 'images/to-do/03.png', 'images/to-do/02.png', 'images/to-do/01.png', 'images/to-do/05.png', 'images/to-do/06.png'],
	},
];
